project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://scconner7.github.io/tidyverse_to_python_blog/ # you must change this appropriately for RSS feeds to work properly
  title: "Tidyverse to Python, Honestly"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/scconner7
format:
  html:
    theme: cyborg
    css: styles.css
